name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag name (e.g., v0.1.3)'
        required: true
        type: string
      release_name:
        description: 'Optional release title'
        required: false
        type: string

jobs:
  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate sitemap and robots.txt
        run: npx next-sitemap

      - name: Set release tag
        id: vars
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            TAG="${{ inputs.tag_name }}"
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Zip release assets
        run: |
          zip -j "site-assets-${{ steps.vars.outputs.tag }}.zip" public/sitemap.xml public/robots.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ inputs.release_name || steps.vars.outputs.tag }}
          files: |
            site-assets-${{ steps.vars.outputs.tag }}.zip
            public/sitemap.xml
            public/robots.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}